### ISSUE TITLE
FlurlHttpException: Call failed with status code 400 (Bad Request): POST https://api.commerce.coinbase.com/charges

### ISSUE THREAD

**Issue by Odigietony** [bchavez/Coinbase.Commerce#4]
Hello, 
I keep getting the 

> FlurlHttpException: Call failed with status code 400 (Bad Request): POST https://api.commerce.coinbase.com/charges

  on this line of code

`var response = await commerceApi.CreateChargeAsync(charge);`
please help!!

**Comment by bchavez** [comment]
Hi @Odigietony,

Thank you for the report.

I ran the [following integration test here](https://github.com/bchavez/Coinbase.Commerce/blob/master/Source/Coinbase.Tests/IntegrationTests.cs#L39-L80) and it completed successfully. I wasn't able to reproduce the `400 Bad Request`. So, I'm not exactly sure why you're getting a mysterious `400 Bad Request`.

I need more information if you'd like me to continue helping you debug the issue.

If you can, please provide:
* A full stack trace of the exception; including inner exceptions.
* Post the code leading up to the `CreateChargeAsync` call. Perhaps there's something wrong with the `charge` object.
* Are you sure your API keys are setup correctly?

Let me know.

Thanks,  
Brian

:walking_man: :walking_woman: **[Missing Persons - Walking in L.A.](https://www.youtube.com/watch?v=R_UpLtGEWoY)**

**Comment by Odigietony** [comment]
Hey! I fixed it.
Given that I want to input amount from my app then send that amount to the api 
I had set the `PricingType = PricingType.NoPrice,
                LocalPrice = new Money { Amount = model.Price, Currency = plan.Currency },`
Instead of 

`PricingType = PricingType.FixedPrice,
                LocalPrice = new Money { Amount = model.Price, Currency = plan.Currency },`

Thank You.
you can close this now.

**Comment by bchavez** [comment]
Wonderful! That's great! Glad you were able to fix the problem! Don't hesitate to ask more questions if you need help! :+1:

-Brian

:briefcase: :necktie: ***["Taking care of business every day... Taking care of business every way..."](https://www.youtube.com/watch?v=mmwic9kFx2c)***
