### ISSUE TITLE
HttpContext does not contain a definition of InputStream. ASP.NET core webhook

### ISSUE THREAD

**Issue by chuksgpfr** [bchavez/Coinbase.Commerce#6]
`var requestSignature = Request.Headers[HeaderNames.WebhookSignature]; Request.InputStream.Seek(0, SeekOrigin.Begin); var json = new StreamReader(Request.InputStream).ReadToEnd();`

HttpContext does not contain a definition of InputStream.

How to solve this

**Comment by bchavez** [comment]
@chuksgpfr , you'll have to find where the input stream is for the request body in your version of ASP.NET. MVC5 or ASP.NET Core. The HttpContext and input stream locations are slightly different between versions. You'll have to give more information about what web framework you're using.

Hope that helps,
Brian
