### ISSUE TITLE
Get currency paid with

### ISSUE THREAD

**Issue by chuksgpfr** [bchavez/Coinbase.Commerce#8]
How do i get the currency the user paid with, either BTC or ETH  and how much is the coin amount  from webhook ?
Something like this. 
`chargeInfo.Pricing["Amount"].Amount`

![charge](https://user-images.githubusercontent.com/27519499/63646451-e78eb300-c70a-11e9-9a91-b3dc4612de8c.png)

**Comment by bchavez** [comment]
@chuksgpfr, I don't know. You need to provide more information.

What does the JSON in the webhook look like?
