### ISSUE TITLE
Null from api request when charge is pending

### ISSUE THREAD

**Issue by Usertothename** [bchavez/Coinbase.Commerce#9]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| NuGet Package            |         this one        |
| .NET Core?                   |         2.1.802   |
| .NET Full Framework?   |          4.6       |
| Windows OS?              |        windows 10          |
| Linux OS?                    |          N/A        |
| Visual Studio?              |         19         |

### What is the expected behavior?
Just get successfully get the charge from api request
### What is the actual behavior?
Request works until the charge status is set to pending
### Any possible solutions?
thats why im here
### How do you reproduce the issue?
Just make a charge send the money and try and request the api when its pending and you get a 
null error json failed to deserialize
### Do you have a unit test that can demonstrate the bug?
No
### Can you identify the location in the source code where the problem exists?
responsee = await commerceApi.GetChargeAsync(response.Data.Code);

**Comment by bchavez** [comment]
[1]:https://github.com/bchavez/Coinbase/issues/62#issuecomment-526868311

1. Provide Fiddler output for the JSON request and JSON response. See [here][1] for setup.
2. Provide a complete failing unit test.

Once you have these two items, please feel free to re-open the issue.

Thank you.
